var EVOL_MAX_SLOTS = 5;
var EVOL_MUTATION_CHANCE = 0.1;
var EVOL_MUTATION_RATE = 0.1;
var EVOL_RANDOM_SPAWN_CHANCE = 0.3;

var LINEAR_MAX_DEVIATION = 65;
var BOUNCER_MAX_DEVIATION = 85;

var SIN_MIN_WAVE_LENGTH = 2;
var SIN_MAX_WAVE_LENGTH = 20;
var SIN_DELTA_WAVE_LENGTH = SIN_MAX_WAVE_LENGTH-SIN_MIN_WAVE_LENGTH;

var SIN_MIN_WAVE_AMPLITUDE = 2;
var SIN_MAX_WAVE_AMPLITUDE = 100;
var SIN_DELTA_WAVE_AMPLITUDE = SIN_MAX_WAVE_AMPLITUDE-SIN_MIN_WAVE_AMPLITUDE;

var MAX_BULLETS = 3;
var MAX_FOES = 4;
var MAX_MOVIMENTS = 3;
var FOE_SPAWN_CHANCE = 0.05;
var FOE_SPEED = 2.5;
var BULLET_RADIUS = 100;

var MAX_FLIES = 10